### PR TITLE
Cleaned up README

### PR DESCRIPTION
**Pull request by ScreamingTaco**
Hey there! I stumbled upon this project and it looked interesting. I fixed some grammatical errors, cleaned up formatting, and clarified some wording in the README.

EDIT: If you decide to accept this PR, would you mind adding the "hacktoberfest" topic so it will be eligible towards my PR count?

### CODE REVIEW

**Comment by souvikhaldar** [comment]
Sure @ScreamingTaco I can do that.
Let me add the topic and verify your request.

**Comment by ScreamingTaco** [comment]
Awesome! Thank you so much!

**Comment by souvikhaldar** [comment]
@ScreamingTaco Can you resolve the conflicts? I'll merge it then. Thanks.

**Comment by ScreamingTaco** [comment]
Alrighty, should be good to go now! Thank you so much for letting me contribute to this project!

**Pull request closed without merging**
